name: CI

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v4
      - name: Install dependencies
        run: yarn install --frozen-lockfile --ignore-scripts
      - name: Run lint check
        run: yarn lint
